version: '3.3'
services:
  post_db:
    image: mongo:${MONVER}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USRNAME}/ui:${VER}
    ports:
      - ${UISRC}:${UIDST}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USRNAME}/post:${VER}
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USRNAME}/comment:${VER}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
